package com.android.pos.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.android.pos.dao.Bills;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BILLS.
*/
public class BillsDao extends AbstractDao<Bills, Long> {

    public static final String TABLENAME = "BILLS";

    /**
     * Properties of entity Bills.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RefId = new Property(1, String.class, "refId", false, "REF_ID");
        public final static Property MerchantId = new Property(2, long.class, "merchantId", false, "MERCHANT_ID");
        public final static Property BillReferenceNo = new Property(3, String.class, "billReferenceNo", false, "BILL_REFERENCE_NO");
        public final static Property BillType = new Property(4, String.class, "billType", false, "BILL_TYPE");
        public final static Property BillDate = new Property(5, java.util.Date.class, "billDate", false, "BILL_DATE");
        public final static Property BillDueDate = new Property(6, java.util.Date.class, "billDueDate", false, "BILL_DUE_DATE");
        public final static Property BillAmount = new Property(7, Float.class, "billAmount", false, "BILL_AMOUNT");
        public final static Property PaymentDate = new Property(8, java.util.Date.class, "paymentDate", false, "PAYMENT_DATE");
        public final static Property Payment = new Property(9, Float.class, "payment", false, "PAYMENT");
        public final static Property SupplierId = new Property(10, Long.class, "supplierId", false, "SUPPLIER_ID");
        public final static Property SupplierName = new Property(11, String.class, "supplierName", false, "SUPPLIER_NAME");
        public final static Property DeliveryDate = new Property(12, java.util.Date.class, "deliveryDate", false, "DELIVERY_DATE");
        public final static Property Remarks = new Property(13, String.class, "remarks", false, "REMARKS");
        public final static Property Status = new Property(14, String.class, "status", false, "STATUS");
        public final static Property UploadStatus = new Property(15, String.class, "uploadStatus", false, "UPLOAD_STATUS");
        public final static Property CreateBy = new Property(16, String.class, "createBy", false, "CREATE_BY");
        public final static Property CreateDate = new Property(17, java.util.Date.class, "createDate", false, "CREATE_DATE");
        public final static Property UpdateBy = new Property(18, String.class, "updateBy", false, "UPDATE_BY");
        public final static Property UpdateDate = new Property(19, java.util.Date.class, "updateDate", false, "UPDATE_DATE");
    };

    private DaoSession daoSession;

    private Query<Bills> supplier_BillsListQuery;

    public BillsDao(DaoConfig config) {
        super(config);
    }
    
    public BillsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BILLS' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'REF_ID' TEXT," + // 1: refId
                "'MERCHANT_ID' INTEGER NOT NULL ," + // 2: merchantId
                "'BILL_REFERENCE_NO' TEXT," + // 3: billReferenceNo
                "'BILL_TYPE' TEXT," + // 4: billType
                "'BILL_DATE' INTEGER," + // 5: billDate
                "'BILL_DUE_DATE' INTEGER," + // 6: billDueDate
                "'BILL_AMOUNT' DECIMAL(10,2)," + // 7: billAmount
                "'PAYMENT_DATE' INTEGER," + // 8: paymentDate
                "'PAYMENT' DECIMAL(10,2)," + // 9: payment
                "'SUPPLIER_ID' INTEGER," + // 10: supplierId
                "'SUPPLIER_NAME' TEXT," + // 11: supplierName
                "'DELIVERY_DATE' INTEGER," + // 12: deliveryDate
                "'REMARKS' TEXT," + // 13: remarks
                "'STATUS' TEXT," + // 14: status
                "'UPLOAD_STATUS' TEXT," + // 15: uploadStatus
                "'CREATE_BY' TEXT," + // 16: createBy
                "'CREATE_DATE' INTEGER," + // 17: createDate
                "'UPDATE_BY' TEXT," + // 18: updateBy
                "'UPDATE_DATE' INTEGER);"); // 19: updateDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BILLS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Bills entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String refId = entity.getRefId();
        if (refId != null) {
            stmt.bindString(2, refId);
        }
        stmt.bindLong(3, entity.getMerchantId());
 
        String billReferenceNo = entity.getBillReferenceNo();
        if (billReferenceNo != null) {
            stmt.bindString(4, billReferenceNo);
        }
 
        String billType = entity.getBillType();
        if (billType != null) {
            stmt.bindString(5, billType);
        }
 
        java.util.Date billDate = entity.getBillDate();
        if (billDate != null) {
            stmt.bindLong(6, billDate.getTime());
        }
 
        java.util.Date billDueDate = entity.getBillDueDate();
        if (billDueDate != null) {
            stmt.bindLong(7, billDueDate.getTime());
        }
 
        Float billAmount = entity.getBillAmount();
        if (billAmount != null) {
            stmt.bindDouble(8, billAmount);
        }
 
        java.util.Date paymentDate = entity.getPaymentDate();
        if (paymentDate != null) {
            stmt.bindLong(9, paymentDate.getTime());
        }
 
        Float payment = entity.getPayment();
        if (payment != null) {
            stmt.bindDouble(10, payment);
        }
 
        Long supplierId = entity.getSupplierId();
        if (supplierId != null) {
            stmt.bindLong(11, supplierId);
        }
 
        String supplierName = entity.getSupplierName();
        if (supplierName != null) {
            stmt.bindString(12, supplierName);
        }
 
        java.util.Date deliveryDate = entity.getDeliveryDate();
        if (deliveryDate != null) {
            stmt.bindLong(13, deliveryDate.getTime());
        }
 
        String remarks = entity.getRemarks();
        if (remarks != null) {
            stmt.bindString(14, remarks);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(15, status);
        }
 
        String uploadStatus = entity.getUploadStatus();
        if (uploadStatus != null) {
            stmt.bindString(16, uploadStatus);
        }
 
        String createBy = entity.getCreateBy();
        if (createBy != null) {
            stmt.bindString(17, createBy);
        }
 
        java.util.Date createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindLong(18, createDate.getTime());
        }
 
        String updateBy = entity.getUpdateBy();
        if (updateBy != null) {
            stmt.bindString(19, updateBy);
        }
 
        java.util.Date updateDate = entity.getUpdateDate();
        if (updateDate != null) {
            stmt.bindLong(20, updateDate.getTime());
        }
    }

    @Override
    protected void attachEntity(Bills entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Bills readEntity(Cursor cursor, int offset) {
        Bills entity = new Bills( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // refId
            cursor.getLong(offset + 2), // merchantId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // billReferenceNo
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // billType
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // billDate
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)), // billDueDate
            cursor.isNull(offset + 7) ? null : cursor.getFloat(offset + 7), // billAmount
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)), // paymentDate
            cursor.isNull(offset + 9) ? null : cursor.getFloat(offset + 9), // payment
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10), // supplierId
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // supplierName
            cursor.isNull(offset + 12) ? null : new java.util.Date(cursor.getLong(offset + 12)), // deliveryDate
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // remarks
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // status
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // uploadStatus
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // createBy
            cursor.isNull(offset + 17) ? null : new java.util.Date(cursor.getLong(offset + 17)), // createDate
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // updateBy
            cursor.isNull(offset + 19) ? null : new java.util.Date(cursor.getLong(offset + 19)) // updateDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Bills entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRefId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMerchantId(cursor.getLong(offset + 2));
        entity.setBillReferenceNo(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBillType(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBillDate(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setBillDueDate(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
        entity.setBillAmount(cursor.isNull(offset + 7) ? null : cursor.getFloat(offset + 7));
        entity.setPaymentDate(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
        entity.setPayment(cursor.isNull(offset + 9) ? null : cursor.getFloat(offset + 9));
        entity.setSupplierId(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
        entity.setSupplierName(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setDeliveryDate(cursor.isNull(offset + 12) ? null : new java.util.Date(cursor.getLong(offset + 12)));
        entity.setRemarks(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setStatus(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setUploadStatus(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setCreateBy(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setCreateDate(cursor.isNull(offset + 17) ? null : new java.util.Date(cursor.getLong(offset + 17)));
        entity.setUpdateBy(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setUpdateDate(cursor.isNull(offset + 19) ? null : new java.util.Date(cursor.getLong(offset + 19)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Bills entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Bills entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "billsList" to-many relationship of Supplier. */
    public List<Bills> _querySupplier_BillsList(Long supplierId) {
        synchronized (this) {
            if (supplier_BillsListQuery == null) {
                QueryBuilder<Bills> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.SupplierId.eq(null));
                queryBuilder.orderRaw("_id ASC");
                supplier_BillsListQuery = queryBuilder.build();
            }
        }
        Query<Bills> query = supplier_BillsListQuery.forCurrentThread();
        query.setParameter(0, supplierId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMerchantDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getSupplierDao().getAllColumns());
            builder.append(" FROM BILLS T");
            builder.append(" LEFT JOIN MERCHANT T0 ON T.'MERCHANT_ID'=T0.'_id'");
            builder.append(" LEFT JOIN SUPPLIER T1 ON T.'SUPPLIER_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Bills loadCurrentDeep(Cursor cursor, boolean lock) {
        Bills entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Merchant merchant = loadCurrentOther(daoSession.getMerchantDao(), cursor, offset);
         if(merchant != null) {
            entity.setMerchant(merchant);
        }
        offset += daoSession.getMerchantDao().getAllColumns().length;

        Supplier supplier = loadCurrentOther(daoSession.getSupplierDao(), cursor, offset);
        entity.setSupplier(supplier);

        return entity;    
    }

    public Bills loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Bills> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Bills> list = new ArrayList<Bills>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Bills> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Bills> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
