package com.android.pos.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.android.pos.dao.Inventory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table INVENTORY.
*/
public class InventoryDao extends AbstractDao<Inventory, Long> {

    public static final String TABLENAME = "INVENTORY";

    /**
     * Properties of entity Inventory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RefId = new Property(1, String.class, "refId", false, "REF_ID");
        public final static Property MerchantId = new Property(2, long.class, "merchantId", false, "MERCHANT_ID");
        public final static Property ProductId = new Property(3, long.class, "productId", false, "PRODUCT_ID");
        public final static Property ProductName = new Property(4, String.class, "productName", false, "PRODUCT_NAME");
        public final static Property ProductCostPrice = new Property(5, Float.class, "productCostPrice", false, "PRODUCT_COST_PRICE");
        public final static Property Quantity = new Property(6, Float.class, "quantity", false, "QUANTITY");
        public final static Property BillId = new Property(7, Long.class, "billId", false, "BILL_ID");
        public final static Property BillReferenceNo = new Property(8, String.class, "billReferenceNo", false, "BILL_REFERENCE_NO");
        public final static Property SupplierId = new Property(9, Long.class, "supplierId", false, "SUPPLIER_ID");
        public final static Property SupplierName = new Property(10, String.class, "supplierName", false, "SUPPLIER_NAME");
        public final static Property InventoryDate = new Property(11, java.util.Date.class, "inventoryDate", false, "INVENTORY_DATE");
        public final static Property Remarks = new Property(12, String.class, "remarks", false, "REMARKS");
        public final static Property Status = new Property(13, String.class, "status", false, "STATUS");
        public final static Property UploadStatus = new Property(14, String.class, "uploadStatus", false, "UPLOAD_STATUS");
        public final static Property CreateBy = new Property(15, String.class, "createBy", false, "CREATE_BY");
        public final static Property CreateDate = new Property(16, java.util.Date.class, "createDate", false, "CREATE_DATE");
        public final static Property UpdateBy = new Property(17, String.class, "updateBy", false, "UPDATE_BY");
        public final static Property UpdateDate = new Property(18, java.util.Date.class, "updateDate", false, "UPDATE_DATE");
    };

    private DaoSession daoSession;

    private Query<Inventory> bills_InventoryListQuery;
    private Query<Inventory> product_InventoryListQuery;
    private Query<Inventory> supplier_InventoryListQuery;

    public InventoryDao(DaoConfig config) {
        super(config);
    }
    
    public InventoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'INVENTORY' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'REF_ID' TEXT," + // 1: refId
                "'MERCHANT_ID' INTEGER NOT NULL ," + // 2: merchantId
                "'PRODUCT_ID' INTEGER NOT NULL ," + // 3: productId
                "'PRODUCT_NAME' TEXT," + // 4: productName
                "'PRODUCT_COST_PRICE' REAL," + // 5: productCostPrice
                "'QUANTITY' REAL," + // 6: quantity
                "'BILL_ID' INTEGER," + // 7: billId
                "'BILL_REFERENCE_NO' TEXT," + // 8: billReferenceNo
                "'SUPPLIER_ID' INTEGER," + // 9: supplierId
                "'SUPPLIER_NAME' TEXT," + // 10: supplierName
                "'INVENTORY_DATE' INTEGER," + // 11: inventoryDate
                "'REMARKS' TEXT," + // 12: remarks
                "'STATUS' TEXT," + // 13: status
                "'UPLOAD_STATUS' TEXT," + // 14: uploadStatus
                "'CREATE_BY' TEXT," + // 15: createBy
                "'CREATE_DATE' INTEGER," + // 16: createDate
                "'UPDATE_BY' TEXT," + // 17: updateBy
                "'UPDATE_DATE' INTEGER);"); // 18: updateDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'INVENTORY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Inventory entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String refId = entity.getRefId();
        if (refId != null) {
            stmt.bindString(2, refId);
        }
        stmt.bindLong(3, entity.getMerchantId());
        stmt.bindLong(4, entity.getProductId());
 
        String productName = entity.getProductName();
        if (productName != null) {
            stmt.bindString(5, productName);
        }
 
        Float productCostPrice = entity.getProductCostPrice();
        if (productCostPrice != null) {
            stmt.bindDouble(6, productCostPrice);
        }
 
        Float quantity = entity.getQuantity();
        if (quantity != null) {
            stmt.bindDouble(7, quantity);
        }
 
        Long billId = entity.getBillId();
        if (billId != null) {
            stmt.bindLong(8, billId);
        }
 
        String billReferenceNo = entity.getBillReferenceNo();
        if (billReferenceNo != null) {
            stmt.bindString(9, billReferenceNo);
        }
 
        Long supplierId = entity.getSupplierId();
        if (supplierId != null) {
            stmt.bindLong(10, supplierId);
        }
 
        String supplierName = entity.getSupplierName();
        if (supplierName != null) {
            stmt.bindString(11, supplierName);
        }
 
        java.util.Date inventoryDate = entity.getInventoryDate();
        if (inventoryDate != null) {
            stmt.bindLong(12, inventoryDate.getTime());
        }
 
        String remarks = entity.getRemarks();
        if (remarks != null) {
            stmt.bindString(13, remarks);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(14, status);
        }
 
        String uploadStatus = entity.getUploadStatus();
        if (uploadStatus != null) {
            stmt.bindString(15, uploadStatus);
        }
 
        String createBy = entity.getCreateBy();
        if (createBy != null) {
            stmt.bindString(16, createBy);
        }
 
        java.util.Date createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindLong(17, createDate.getTime());
        }
 
        String updateBy = entity.getUpdateBy();
        if (updateBy != null) {
            stmt.bindString(18, updateBy);
        }
 
        java.util.Date updateDate = entity.getUpdateDate();
        if (updateDate != null) {
            stmt.bindLong(19, updateDate.getTime());
        }
    }

    @Override
    protected void attachEntity(Inventory entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Inventory readEntity(Cursor cursor, int offset) {
        Inventory entity = new Inventory( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // refId
            cursor.getLong(offset + 2), // merchantId
            cursor.getLong(offset + 3), // productId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // productName
            cursor.isNull(offset + 5) ? null : cursor.getFloat(offset + 5), // productCostPrice
            cursor.isNull(offset + 6) ? null : cursor.getFloat(offset + 6), // quantity
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // billId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // billReferenceNo
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9), // supplierId
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // supplierName
            cursor.isNull(offset + 11) ? null : new java.util.Date(cursor.getLong(offset + 11)), // inventoryDate
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // remarks
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // status
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // uploadStatus
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // createBy
            cursor.isNull(offset + 16) ? null : new java.util.Date(cursor.getLong(offset + 16)), // createDate
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // updateBy
            cursor.isNull(offset + 18) ? null : new java.util.Date(cursor.getLong(offset + 18)) // updateDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Inventory entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRefId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMerchantId(cursor.getLong(offset + 2));
        entity.setProductId(cursor.getLong(offset + 3));
        entity.setProductName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setProductCostPrice(cursor.isNull(offset + 5) ? null : cursor.getFloat(offset + 5));
        entity.setQuantity(cursor.isNull(offset + 6) ? null : cursor.getFloat(offset + 6));
        entity.setBillId(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setBillReferenceNo(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSupplierId(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
        entity.setSupplierName(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setInventoryDate(cursor.isNull(offset + 11) ? null : new java.util.Date(cursor.getLong(offset + 11)));
        entity.setRemarks(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setStatus(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setUploadStatus(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setCreateBy(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setCreateDate(cursor.isNull(offset + 16) ? null : new java.util.Date(cursor.getLong(offset + 16)));
        entity.setUpdateBy(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setUpdateDate(cursor.isNull(offset + 18) ? null : new java.util.Date(cursor.getLong(offset + 18)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Inventory entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Inventory entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "inventoryList" to-many relationship of Bills. */
    public List<Inventory> _queryBills_InventoryList(Long billId) {
        synchronized (this) {
            if (bills_InventoryListQuery == null) {
                QueryBuilder<Inventory> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.BillId.eq(null));
                queryBuilder.orderRaw("PRODUCT_NAME ASC");
                bills_InventoryListQuery = queryBuilder.build();
            }
        }
        Query<Inventory> query = bills_InventoryListQuery.forCurrentThread();
        query.setParameter(0, billId);
        return query.list();
    }

    /** Internal query to resolve the "inventoryList" to-many relationship of Product. */
    public List<Inventory> _queryProduct_InventoryList(long productId) {
        synchronized (this) {
            if (product_InventoryListQuery == null) {
                QueryBuilder<Inventory> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ProductId.eq(null));
                queryBuilder.orderRaw("_id ASC");
                product_InventoryListQuery = queryBuilder.build();
            }
        }
        Query<Inventory> query = product_InventoryListQuery.forCurrentThread();
        query.setParameter(0, productId);
        return query.list();
    }

    /** Internal query to resolve the "inventoryList" to-many relationship of Supplier. */
    public List<Inventory> _querySupplier_InventoryList(Long supplierId) {
        synchronized (this) {
            if (supplier_InventoryListQuery == null) {
                QueryBuilder<Inventory> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.SupplierId.eq(null));
                queryBuilder.orderRaw("_id ASC");
                supplier_InventoryListQuery = queryBuilder.build();
            }
        }
        Query<Inventory> query = supplier_InventoryListQuery.forCurrentThread();
        query.setParameter(0, supplierId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMerchantDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getProductDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getBillsDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T3", daoSession.getSupplierDao().getAllColumns());
            builder.append(" FROM INVENTORY T");
            builder.append(" LEFT JOIN MERCHANT T0 ON T.'MERCHANT_ID'=T0.'_id'");
            builder.append(" LEFT JOIN PRODUCT T1 ON T.'PRODUCT_ID'=T1.'_id'");
            builder.append(" LEFT JOIN BILLS T2 ON T.'BILL_ID'=T2.'_id'");
            builder.append(" LEFT JOIN SUPPLIER T3 ON T.'SUPPLIER_ID'=T3.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Inventory loadCurrentDeep(Cursor cursor, boolean lock) {
        Inventory entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Merchant merchant = loadCurrentOther(daoSession.getMerchantDao(), cursor, offset);
         if(merchant != null) {
            entity.setMerchant(merchant);
        }
        offset += daoSession.getMerchantDao().getAllColumns().length;

        Product product = loadCurrentOther(daoSession.getProductDao(), cursor, offset);
         if(product != null) {
            entity.setProduct(product);
        }
        offset += daoSession.getProductDao().getAllColumns().length;

        Bills bills = loadCurrentOther(daoSession.getBillsDao(), cursor, offset);
        entity.setBills(bills);
        offset += daoSession.getBillsDao().getAllColumns().length;

        Supplier supplier = loadCurrentOther(daoSession.getSupplierDao(), cursor, offset);
        entity.setSupplier(supplier);

        return entity;    
    }

    public Inventory loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Inventory> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Inventory> list = new ArrayList<Inventory>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Inventory> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Inventory> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
