package com.android.pos.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.android.pos.dao.Merchant;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MERCHANT.
*/
public class MerchantDao extends AbstractDao<Merchant, Long> {

    public static final String TABLENAME = "MERCHANT";

    /**
     * Properties of entity Merchant.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Type = new Property(2, String.class, "type", false, "TYPE");
        public final static Property Address = new Property(3, String.class, "address", false, "ADDRESS");
        public final static Property ContactName = new Property(4, String.class, "contactName", false, "CONTACT_NAME");
        public final static Property ContactTelephone = new Property(5, String.class, "contactTelephone", false, "CONTACT_TELEPHONE");
        public final static Property LoginId = new Property(6, String.class, "loginId", false, "LOGIN_ID");
        public final static Property Password = new Property(7, String.class, "password", false, "PASSWORD");
        public final static Property PeriodStart = new Property(8, java.util.Date.class, "periodStart", false, "PERIOD_START");
        public final static Property PeriodEnd = new Property(9, java.util.Date.class, "periodEnd", false, "PERIOD_END");
        public final static Property TaxPercentage = new Property(10, Integer.class, "taxPercentage", false, "TAX_PERCENTAGE");
        public final static Property ServiceChargePercentage = new Property(11, Integer.class, "serviceChargePercentage", false, "SERVICE_CHARGE_PERCENTAGE");
        public final static Property IsLogin = new Property(12, Boolean.class, "isLogin", false, "IS_LOGIN");
        public final static Property Status = new Property(13, String.class, "status", false, "STATUS");
        public final static Property UploadStatus = new Property(14, String.class, "uploadStatus", false, "UPLOAD_STATUS");
        public final static Property CreateBy = new Property(15, String.class, "createBy", false, "CREATE_BY");
        public final static Property CreateDate = new Property(16, java.util.Date.class, "createDate", false, "CREATE_DATE");
        public final static Property UpdateBy = new Property(17, String.class, "updateBy", false, "UPDATE_BY");
        public final static Property UpdateDate = new Property(18, java.util.Date.class, "updateDate", false, "UPDATE_DATE");
    };

    private DaoSession daoSession;


    public MerchantDao(DaoConfig config) {
        super(config);
    }
    
    public MerchantDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MERCHANT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NAME' TEXT NOT NULL ," + // 1: name
                "'TYPE' TEXT," + // 2: type
                "'ADDRESS' TEXT," + // 3: address
                "'CONTACT_NAME' TEXT," + // 4: contactName
                "'CONTACT_TELEPHONE' TEXT," + // 5: contactTelephone
                "'LOGIN_ID' TEXT," + // 6: loginId
                "'PASSWORD' TEXT," + // 7: password
                "'PERIOD_START' INTEGER," + // 8: periodStart
                "'PERIOD_END' INTEGER," + // 9: periodEnd
                "'TAX_PERCENTAGE' INTEGER," + // 10: taxPercentage
                "'SERVICE_CHARGE_PERCENTAGE' INTEGER," + // 11: serviceChargePercentage
                "'IS_LOGIN' INTEGER," + // 12: isLogin
                "'STATUS' TEXT," + // 13: status
                "'UPLOAD_STATUS' TEXT," + // 14: uploadStatus
                "'CREATE_BY' TEXT," + // 15: createBy
                "'CREATE_DATE' INTEGER," + // 16: createDate
                "'UPDATE_BY' TEXT," + // 17: updateBy
                "'UPDATE_DATE' INTEGER);"); // 18: updateDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MERCHANT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Merchant entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(3, type);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(4, address);
        }
 
        String contactName = entity.getContactName();
        if (contactName != null) {
            stmt.bindString(5, contactName);
        }
 
        String contactTelephone = entity.getContactTelephone();
        if (contactTelephone != null) {
            stmt.bindString(6, contactTelephone);
        }
 
        String loginId = entity.getLoginId();
        if (loginId != null) {
            stmt.bindString(7, loginId);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(8, password);
        }
 
        java.util.Date periodStart = entity.getPeriodStart();
        if (periodStart != null) {
            stmt.bindLong(9, periodStart.getTime());
        }
 
        java.util.Date periodEnd = entity.getPeriodEnd();
        if (periodEnd != null) {
            stmt.bindLong(10, periodEnd.getTime());
        }
 
        Integer taxPercentage = entity.getTaxPercentage();
        if (taxPercentage != null) {
            stmt.bindLong(11, taxPercentage);
        }
 
        Integer serviceChargePercentage = entity.getServiceChargePercentage();
        if (serviceChargePercentage != null) {
            stmt.bindLong(12, serviceChargePercentage);
        }
 
        Boolean isLogin = entity.getIsLogin();
        if (isLogin != null) {
            stmt.bindLong(13, isLogin ? 1l: 0l);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(14, status);
        }
 
        String uploadStatus = entity.getUploadStatus();
        if (uploadStatus != null) {
            stmt.bindString(15, uploadStatus);
        }
 
        String createBy = entity.getCreateBy();
        if (createBy != null) {
            stmt.bindString(16, createBy);
        }
 
        java.util.Date createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindLong(17, createDate.getTime());
        }
 
        String updateBy = entity.getUpdateBy();
        if (updateBy != null) {
            stmt.bindString(18, updateBy);
        }
 
        java.util.Date updateDate = entity.getUpdateDate();
        if (updateDate != null) {
            stmt.bindLong(19, updateDate.getTime());
        }
    }

    @Override
    protected void attachEntity(Merchant entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Merchant readEntity(Cursor cursor, int offset) {
        Merchant entity = new Merchant( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // type
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // address
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // contactName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // contactTelephone
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // loginId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // password
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)), // periodStart
            cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)), // periodEnd
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // taxPercentage
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // serviceChargePercentage
            cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0, // isLogin
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // status
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // uploadStatus
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // createBy
            cursor.isNull(offset + 16) ? null : new java.util.Date(cursor.getLong(offset + 16)), // createDate
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // updateBy
            cursor.isNull(offset + 18) ? null : new java.util.Date(cursor.getLong(offset + 18)) // updateDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Merchant entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAddress(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setContactName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setContactTelephone(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setLoginId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPassword(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPeriodStart(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
        entity.setPeriodEnd(cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)));
        entity.setTaxPercentage(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setServiceChargePercentage(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setIsLogin(cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0);
        entity.setStatus(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setUploadStatus(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setCreateBy(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setCreateDate(cursor.isNull(offset + 16) ? null : new java.util.Date(cursor.getLong(offset + 16)));
        entity.setUpdateBy(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setUpdateDate(cursor.isNull(offset + 18) ? null : new java.util.Date(cursor.getLong(offset + 18)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Merchant entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Merchant entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
