package com.android.pos.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.android.pos.dao.Orders;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ORDERS.
*/
public class OrdersDao extends AbstractDao<Orders, Long> {

    public static final String TABLENAME = "ORDERS";

    /**
     * Properties of entity Orders.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RefId = new Property(1, String.class, "refId", false, "REF_ID");
        public final static Property MerchantId = new Property(2, long.class, "merchantId", false, "MERCHANT_ID");
        public final static Property OrderNo = new Property(3, String.class, "orderNo", false, "ORDER_NO");
        public final static Property OrderDate = new Property(4, java.util.Date.class, "orderDate", false, "ORDER_DATE");
        public final static Property OrderType = new Property(5, String.class, "orderType", false, "ORDER_TYPE");
        public final static Property OrderReference = new Property(6, String.class, "orderReference", false, "ORDER_REFERENCE");
        public final static Property WaitressId = new Property(7, Long.class, "waitressId", false, "WAITRESS_ID");
        public final static Property WaitressName = new Property(8, String.class, "waitressName", false, "WAITRESS_NAME");
        public final static Property CustomerId = new Property(9, Long.class, "customerId", false, "CUSTOMER_ID");
        public final static Property CustomerName = new Property(10, String.class, "customerName", false, "CUSTOMER_NAME");
        public final static Property Status = new Property(11, String.class, "status", false, "STATUS");
        public final static Property UploadStatus = new Property(12, String.class, "uploadStatus", false, "UPLOAD_STATUS");
    };

    private DaoSession daoSession;


    public OrdersDao(DaoConfig config) {
        super(config);
    }
    
    public OrdersDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ORDERS' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'REF_ID' TEXT," + // 1: refId
                "'MERCHANT_ID' INTEGER NOT NULL ," + // 2: merchantId
                "'ORDER_NO' TEXT," + // 3: orderNo
                "'ORDER_DATE' INTEGER NOT NULL ," + // 4: orderDate
                "'ORDER_TYPE' TEXT," + // 5: orderType
                "'ORDER_REFERENCE' TEXT," + // 6: orderReference
                "'WAITRESS_ID' INTEGER," + // 7: waitressId
                "'WAITRESS_NAME' TEXT," + // 8: waitressName
                "'CUSTOMER_ID' INTEGER," + // 9: customerId
                "'CUSTOMER_NAME' TEXT," + // 10: customerName
                "'STATUS' TEXT," + // 11: status
                "'UPLOAD_STATUS' TEXT);"); // 12: uploadStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ORDERS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Orders entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String refId = entity.getRefId();
        if (refId != null) {
            stmt.bindString(2, refId);
        }
        stmt.bindLong(3, entity.getMerchantId());
 
        String orderNo = entity.getOrderNo();
        if (orderNo != null) {
            stmt.bindString(4, orderNo);
        }
        stmt.bindLong(5, entity.getOrderDate().getTime());
 
        String orderType = entity.getOrderType();
        if (orderType != null) {
            stmt.bindString(6, orderType);
        }
 
        String orderReference = entity.getOrderReference();
        if (orderReference != null) {
            stmt.bindString(7, orderReference);
        }
 
        Long waitressId = entity.getWaitressId();
        if (waitressId != null) {
            stmt.bindLong(8, waitressId);
        }
 
        String waitressName = entity.getWaitressName();
        if (waitressName != null) {
            stmt.bindString(9, waitressName);
        }
 
        Long customerId = entity.getCustomerId();
        if (customerId != null) {
            stmt.bindLong(10, customerId);
        }
 
        String customerName = entity.getCustomerName();
        if (customerName != null) {
            stmt.bindString(11, customerName);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(12, status);
        }
 
        String uploadStatus = entity.getUploadStatus();
        if (uploadStatus != null) {
            stmt.bindString(13, uploadStatus);
        }
    }

    @Override
    protected void attachEntity(Orders entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Orders readEntity(Cursor cursor, int offset) {
        Orders entity = new Orders( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // refId
            cursor.getLong(offset + 2), // merchantId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // orderNo
            new java.util.Date(cursor.getLong(offset + 4)), // orderDate
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // orderType
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // orderReference
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // waitressId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // waitressName
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9), // customerId
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // customerName
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // status
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // uploadStatus
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Orders entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRefId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMerchantId(cursor.getLong(offset + 2));
        entity.setOrderNo(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setOrderDate(new java.util.Date(cursor.getLong(offset + 4)));
        entity.setOrderType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOrderReference(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setWaitressId(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setWaitressName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCustomerId(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
        entity.setCustomerName(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setStatus(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setUploadStatus(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Orders entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Orders entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMerchantDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getEmployeeDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getCustomerDao().getAllColumns());
            builder.append(" FROM ORDERS T");
            builder.append(" LEFT JOIN MERCHANT T0 ON T.'MERCHANT_ID'=T0.'_id'");
            builder.append(" LEFT JOIN EMPLOYEE T1 ON T.'WAITRESS_ID'=T1.'_id'");
            builder.append(" LEFT JOIN CUSTOMER T2 ON T.'CUSTOMER_ID'=T2.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Orders loadCurrentDeep(Cursor cursor, boolean lock) {
        Orders entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Merchant merchant = loadCurrentOther(daoSession.getMerchantDao(), cursor, offset);
         if(merchant != null) {
            entity.setMerchant(merchant);
        }
        offset += daoSession.getMerchantDao().getAllColumns().length;

        Employee employee = loadCurrentOther(daoSession.getEmployeeDao(), cursor, offset);
        entity.setEmployee(employee);
        offset += daoSession.getEmployeeDao().getAllColumns().length;

        Customer customer = loadCurrentOther(daoSession.getCustomerDao(), cursor, offset);
        entity.setCustomer(customer);

        return entity;    
    }

    public Orders loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Orders> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Orders> list = new ArrayList<Orders>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Orders> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Orders> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
